spring:
  profiles:
    active: ${spring.profiles.default:local}

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  tomcat:
    use-relative-redirects: true
  servlet:
    encoding:
      charset: UTF-8
      force: true


logging:
  level:
    org.springframework.orm.jpa: DEBUG
    com.zaxxer.hikari: DEBUG
