spring:
  datasource:
    hikari:
      common:
        jdbc-url: "jdbc:mariadb://localhost:3306/common"
        username: "root"
        password: "1111"
        pool-name: "hikariPool"
        maximum-pool-size: "10"
      tenant:
        driver-class-name: "org.mariadb.jdbc.Driver"
        jdbc-url: "jdbc:mariadb://localhost:3306/test"
        username: "root"
        password: "1111"
        pool-name: "hikariPool"
        maximum-pool-size: "10"
