spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:test
      jdbc-url: jdbc:h2:~/test
      username: "sa"
      password: ""
      pool-name: "hikariPool"
      maximum-pool-size: "1"
  h2:
    console:
      enabled: true
      path: /h2-console