spring:
  profiles:
    active: ${spring.profiles.default:local}

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    use-relative-redirects: true
  servlet:
    encoding:
      charset: UTF-8
      force: true