spring:
  datasource:
    hikari:
      driver-class-name: "org.mariadb.jdbc.Driver"
      jdbc-url: "jdbc:mariadb://localhost:3306/test"
      username: "root"
      password: "1111"
      pool-name: "hikariPool"
      maximum-pool-size: "1"
  liquibase:
    change-log: classpath:/database/tenant/table_init.sql